[global]

[streamrelay]
stream_relay_enabled          = 1
stream_relay_user             = relay
stream_relay_ctab             = 098D

[dvbapi]
enabled                       = 1
user                          = dvbapi
au                            = 1

[webif]
httpport                      = 8888
httphelplang                  = de
httprefresh                   = 10
httppollrefresh               = 10
httpallowed                   = 127.0.0.1,0.0.0.0-255.255.255.255,fd00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,2000::-3fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,::1
httphideidleclients           = 0
